select
  cast(year as varchar) as year,
  lpad(cast(month as varchar), 2, '0') as month,
  {{ month_key_expr('year', 'month') }} as month_key,
  cast(bucket as varchar) as bucket,
  cast(game_uuid as varchar) as game_uuid,
  cast(game_url as varchar) as game_url,
  cast(game_date as varchar) as game_date,
  cast(end_time_utc as varchar) as end_time_utc,
  cast(time_class as varchar) as time_class,
  cast(time_control as varchar) as time_control,
  rated,
  cast(rules as varchar) as rules,
  cast(opening_url as varchar) as opening_url,
  cast(opening_name as varchar) as opening_name,
  cast(initial_setup as varchar) as initial_setup,
  cast(fen as varchar) as fen,
  has_pgn,
  has_tcn,
  has_accuracies,
  cast(white_username as varchar) as white_username,
  cast(white_title as varchar) as white_title,
  cast(white_rating as double) as white_rating,
  cast(white_result as varchar) as white_result,
  cast(white_score as double) as white_score,
  cast(white_accuracy as double) as white_accuracy,
  cast(black_username as varchar) as black_username,
  cast(black_title as varchar) as black_title,
  cast(black_rating as double) as black_rating,
  cast(black_result as varchar) as black_result,
  cast(black_score as double) as black_score,
  cast(black_accuracy as double) as black_accuracy,
  cast(winner_color as varchar) as winner_color,
  cast(source_key_count as integer) as source_key_count,
  cast(source_player_count as integer) as source_player_count,
  source_player_usernames
from {{ source('bronze_external', 'games_core_external') }}
