select
  cast(year as varchar) as year,
  lpad(cast(month as varchar), 2, '0') as month,
  {{ month_key_expr('year', 'month') }} as month_key,
  cast(bucket as varchar) as bucket,
  cast(game_uuid as varchar) as game_uuid,
  cast(game_url as varchar) as game_url,
  cast(game_date as varchar) as game_date,
  cast(end_time_utc as varchar) as end_time_utc,
  cast(time_class as varchar) as time_class,
  cast(time_control as varchar) as time_control,
  rated,
  cast(rules as varchar) as rules,
  cast(opening_url as varchar) as opening_url,
  cast(opening_name as varchar) as opening_name,
  cast(winner_color as varchar) as winner_color,
  has_pgn,
  has_tcn,
  has_accuracies,
  cast(username as varchar) as username,
  cast(title as varchar) as title,
  cast(opponent_username as varchar) as opponent_username,
  cast(opponent_title as varchar) as opponent_title,
  cast(color as varchar) as color,
  cast(rating as double) as rating,
  cast(opponent_rating as double) as opponent_rating,
  cast(rating_diff as double) as rating_diff,
  cast(result as varchar) as result,
  cast(score as double) as score,
  cast(accuracy as double) as accuracy,
  cast(opponent_accuracy as double) as opponent_accuracy,
  is_titled_player,
  is_titled_opponent
from {{ source('bronze_external', 'player_game_facts_external') }}
